image: docker

services:
  - docker:dind
before_script:
    - apk add --update py-pip
    - apk add --update python-dev libffi-dev openssl-dev gcc libc-dev make
    #- apk add --no-cache python-pip
    - pip install docker-compose
    #- docker login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD"

stages:
  - deploy

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual
