version: '3.7'

services:
  webspa:
    image: paymentgateway/webspa
    build:
      context: .
      dockerfile: src/WebApp/WebSPA/Dockerfile
  identity.api:
    image: paymentgateway/identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
  monitoring.api:
    image: paymentgateway/monitoringapi
    build:
      context: .
      dockerfile: src/Services/Monitoring/Monitoring.API/Dockerfile
  payment.api:
    image: paymentgateway/paymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
  postgres:
    image: postgres:11.2-alpine
  pgadmin:
    image: nphung/pgadmin
  rabbitmq:
    image: rabbitmq:3.7.13-management-alpine


